#code generated by copilot llm

from fastapi import FastAPI, WebSocket
from app.models.score import Score
from app.db import engine, Base, SessionLocal
from fastapi.middleware.cors import CORSMiddleware



#IMPORT ROUTERS
from app.api.competitors import router as competitors_router
from app.api.judges import router as judges_router
from app.api.events import router as events_router
from app.api.heats import router as heats_router
from app.api.heat_competitors import router as heat_competitors_router
from app.api.scores import router as scores_router
from app.api.websocket import router as websocket_router
from app.api.spectator import router as spectators_router


# Import ALL models so SQLAlchemy knows them
from app.models.event import Event
from app.models.heat import Heat
from app.models.competitor import Competitor
from app.models.heat_competitor import HeatCompetitor
from app.models.judge import Judge
from app.models.score import Score


app = FastAPI()
Base.metadata.create_all(bind=engine)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # allow all origins for development
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


app.include_router(spectators_router)
app.include_router(heat_competitors_router)
app.include_router(judges_router)
app.include_router(scores_router)
app.include_router(events_router)
app.include_router(heats_router)
app.include_router(competitors_router)

app.include_router(websocket_router)

@app.get("/")
def root():
    return {"message": "Welcome to the Surf Live Scoring API!"}

@app.get("/heats/{heat_id}")
def get_heat(heat_id: int):
    return {"heat_id": heat_id, "scores": []}

@app.websocket("/ws/heat/{heat_id}")
async def heat_updates(websocket: WebSocket, heat_id: int):
    await websocket.accept()
    await websocket.send_text(f"Connected to heat {heat_id}")