#code generated by copilot llm

from fastapi import FastAPI, WebSocket
from app.models.score import Score
from app.api.scores import router as scores_router
from app.db import engine, Base, SessionLocal

# Import ALL models so SQLAlchemy knows them
from app.models.event import Event
from app.models.heat import Heat
from app.models.competitor import Competitor
from app.models.heat_competitor import HeatCompetitor
from app.models.judge import Judge
from app.models.score import Score

app = FastAPI()
Base.metadata.create_all(bind=engine)

app.include_router(scores_router)

@app.get("/")
def root():
    return {"message": "Welcome to the Surf Live Scoring API!"}

@app.get("/heats/{heat_id}")
def get_heat(heat_id: int):
    return {"heat_id": heat_id, "scores": []}

@app.websocket("/ws/heat/{heat_id}")
async def heat_updates(websocket: WebSocket, heat_id: int):
    await websocket.accept()
    await websocket.send_text(f"Connected to heat {heat_id}")